# Generated by Django 5.2.17 on 2026-08-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('breakfast', '아침'), ('lunch', '점심'), ('dinner', '저녁'), ('snack', '간식')], max_length=20)),
                ('portion_size', models.CharField(choices=[('small', '소량'), ('medium', '보통'), ('large', '많음')], max_length=20)),
                ('meal_time', models.DateTimeField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-meal_time', '-created_at'],
            },
        ),
    ]
