# Generated by Django 5.2.17 on 2026-08-09 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort_level', models.CharField(choices=[('comfortable', '편안함'), ('slightly_uncomfortable', '약간 불편함'), ('very_uncomfortable', '많이 불편함')], max_length=30)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('symptom_timing', models.CharField(blank=True, choices=[('within_30_minutes', '식후 30분 이내'), ('within_3_hours', '식후 1~3시간 후'), ('unknown', '잘 모르겠음')], max_length=30)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='meals.mealrecord')),
            ],
        ),
    ]
