import { useEffect, useState } from 'react'
import { createMealRecord, getMealRecords } from './services/meals'

const TAGS = ['매운 음식', '기름진 음식', '유제품', '밀가루', '카페인', '자극 적음', '국물', '밥 중심']
const MEAL_TYPES = [{value: 'breakfast', label: '아침'}, {value: 'lunch', label: '점심'}, {value: 'dinner', label: '저녁'}, {value: 'snack', label: '간식'}]
const PORTIONS = [{value: 'small', label: '소량'}, {value: 'medium', label: '보통'}, {value: 'large', label: '많음'}]
const localDateTimeValue = () => { const now = new Date(); return new Date(now - now.getTimezoneOffset() * 60000).toISOString().slice(0, 16) }
const formatTime = (value) => new Intl.DateTimeFormat('ko-KR', {dateStyle: 'medium', timeStyle: 'short'}).format(new Date(value))

export default function App() {
  const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  const [form, setForm] = useState({menu_name: '', meal_type: 'lunch', portion_size: 'medium', meal_time: localDateTimeValue(), tags: [], note: ''})
  useEffect(() => { getMealRecords().then(setRecords).catch((error) => setMessage(error.message)).finally(() => setLoading(false)) }, [])
  const updateField = ({target: {name, value}}) => setForm((current) => ({...current, [name]: value}))
  const toggleTag = (tag) => setForm((current) => ({...current, tags: current.tags.includes(tag) ? current.tags.filter((item) => item !== tag) : [...current.tags, tag]}))
  async function submit(event) { event.preventDefault(); setSaving(true); setMessage(''); try { const created = await createMealRecord({...form, meal_time: new Date(form.meal_time).toISOString()}); setRecords((current) => [created, ...current]); setForm({menu_name: '', meal_type: 'lunch', portion_size: 'medium', meal_time: localDateTimeValue(), tags: [], note: ''}); setMessage('식사 기록을 저장했어요. 식후 상태 기록은 다음 단계에서 연결됩니다.') } catch (error) { setMessage(error.message) } finally { setSaving(false) } }
  return <main className="page-shell"><header><p className="eyebrow">IBS WELLNESS · MVP</p><h1>오늘 먹은 식사를<br />가볍게 남겨보세요.</h1><p>기록이 쌓이면 나에게 편안한 식사 패턴을 함께 찾아드릴게요.</p></header><section className="card"><div className="section-heading"><span>01</span><h2>식사 기록</h2></div><form onSubmit={submit}><label>메뉴명 <b>*</b><input name="menu_name" value={form.menu_name} onChange={updateField} placeholder="예: 비빔밥" maxLength="100" required /></label><div className="field-grid"><label>식사 유형 <b>*</b><select name="meal_type" value={form.meal_type} onChange={updateField}>{MEAL_TYPES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>식사 시간 <b>*</b><input type="datetime-local" name="meal_time" value={form.meal_time} onChange={updateField} required /></label></div><fieldset><legend>섭취량 <b>*</b></legend><div className="choice-row">{PORTIONS.map((item) => <label className="choice" key={item.value}><input type="radio" name="portion_size" value={item.value} checked={form.portion_size === item.value} onChange={updateField} /><span>{item.label}</span></label>)}</div></fieldset><fieldset><legend>음식 특성 <em>선택</em></legend><div className="tag-list">{TAGS.map((tag) => <button type="button" className={form.tags.includes(tag) ? 'tag selected' : 'tag'} key={tag} onClick={() => toggleTag(tag)}>{tag}</button>)}</div></fieldset><label>메모 <em>선택</em><textarea name="note" value={form.note} onChange={updateField} placeholder="양념을 적게 넣었어요처럼 간단히 남겨보세요." maxLength="500" rows="3" /></label><button className="submit-button" disabled={saving}>{saving ? '저장 중...' : '식사 기록 저장하기'}</button>{message && <p className="message">{message}</p>}</form></section><section className="card records"><div className="section-heading"><span>최근</span><h2>나의 식사 기록</h2></div>{loading ? <p>기록을 불러오는 중이에요.</p> : records.length === 0 ? <p>첫 식사를 기록해보세요. 다음 단계에서 식후 상태도 연결할 수 있어요.</p> : <ul>{records.map((record) => <li key={record.id}><strong>{record.menu_name}</strong><p>{MEAL_TYPES.find((item) => item.value === record.meal_type)?.label} · {PORTIONS.find((item) => item.value === record.portion_size)?.label} · {formatTime(record.meal_time)}</p>{record.tags.length > 0 && <small>{record.tags.join(' · ')}</small>}</li>)}</ul>}</section><footer>식사 기록은 나의 몸을 이해하기 위한 참고 정보이며, 의료적 진단이나 치료를 대체하지 않습니다.</footer></main>
}
